### ISSUE TITLE
Improve the speed performance

### ISSUE THREAD

**Issue by meggarr** [rancher/ipsec#12]
Hi there,

Is it possible to change the default ESP protocol to something faster?

E.g. according to https://wiki.strongswan.org/projects/strongswan/wiki/RaspberryPi2Benchmark `aes128-sha1` is about about 30% faster than `aes128gcm128` on Raspberry PI2.

Thanks?

**Comment by meggarr** [comment]
Also, there would be improvements in pub key algorithm per https://wiki.strongswan.org/projects/strongswan/wiki/PublicKeySpeed

**Comment by meggarr** [comment]
@leodotcloud

**Comment by vincent99** [comment]
You can certainly change it in the config of your own image, but:

- we do not support ARM
- the default setup can already saturate a gigabit port on an x86 core
- SHA-1 is deprecated
- key exchange is a small occasional setup cost and not a factor in the ongoing actual communication between 2 hosts
- we are focused on 2.x; 1.x is in maintenance mode for important bug or security fixes.
